# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-11 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contest_id', models.IntegerField()),
                ('hacker_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_accept_submissions', models.IntegerField()),
                ('total_submissions', models.IntegerField()),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Challenges')),
            ],
        ),
        migrations.CreateModel(
            name='ViewStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField()),
                ('total_unique_views', models.IntegerField()),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Challenges')),
            ],
        ),
        migrations.AddField(
            model_name='colleges',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Contests'),
        ),
        migrations.AddField(
            model_name='challenges',
            name='college_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ps.Colleges'),
        ),
    ]
